#!/usr/local/bin/perl -w

eval 'exec /usr/local/bin/perl -w -S $0 ${1+"$@"}'
    if 0; # not running under some shell

eval 'exec /usr/local/bin/perl -w -S $0 ${1+"$@"}'
    if 0; # not running under some shell

eval 'exec /usr/local/bin/perl -w -S $0 ${1+"$@"}'
    if 0; # not running under some shell

use strict;
use FindBin;
use File::Spec::Functions;

my $file = catfile($FindBin::Bin, updir, 'data', "output.txt");

open F, ">$file" or die "Cannot open '$file': $!\n";
binmode F, ':raw';
binmode STDIN, ':raw';
while (<STDIN>) { print F }
close F;
